src/Entity/Archive.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArchiveRepository")
 */
class Archive
{
    const BEFORE_REPAIR_UPLOAD_IMAGE_TYPE = 'Ajout Image';
    const AFTER_REPAIR_UPLOAD_IMAGE_TYPE = 'Ajout Image';
    const DEVIS_REPARATION_UPLOAD_TYPE = 'Ajout devis';
    const ADD_BILL_TYPE = 'Ajout facture';
    const DELETE_BILL_TYPE = 'Suppression facture';
    const ADD_CRASH_POINT_TYPE = 'Ajout point de choc';
    const RESET_CRASH_POINTS_TYPE = 'Suppression points de choc';
    const DELETE_ATTACHED_FILE_TYPE = 'Suppression pièces jointes';
    const TRANSITION_TYPE = 'Changement d\'état';
    const SELLING_REPORT_TYPE = 'Ajout contrat';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $action_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $action;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Folder", inversedBy="archives")
     * @ORM\JoinColumn(nullable=false)
     */
    private $folder;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Bill", inversedBy="archives")
     */
    private $bill;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\WreckageReport", inversedBy="archives")
     */
    private $wreckageReport;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AttachedFile", inversedBy="archives")
     */
    private $attachedFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="archives")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getActionDate(): ?\DateTimeInterface
    {
        return $this->action_date;
    }

    public function setActionDate(\DateTimeInterface $action_date): self
    {
        $this->action_date = $action_date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAction(): ?string
    {
        return $this->action;
    }

    public function setAction(string $action): self
    {
        $this->action = $action;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getFolder(): ?Folder
    {
        return $this->folder;
    }

    public function setFolder(?Folder $folder): self
    {
        $this->folder = $folder;

        return $this;
    }

    public function getBill(): ?Bill
    {
        return $this->bill;
    }

    public function setBill(?Bill $bill): self
    {
        $this->bill = $bill;

        return $this;
    }

    public function getWreckageReport(): ?WreckageReport
    {
        return $this->wreckageReport;
    }

    public function setWreckageReport(?WreckageReport $wreckageReport): self
    {
        $this->wreckageReport = $wreckageReport;

        return $this;
    }

    public function getAttachedFile(): ?AttachedFile
    {
        return $this->attachedFile;
    }

    public function setAttachedFile(?AttachedFile $attachedFile): self
    {
        $this->attachedFile = $attachedFile;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Folder.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FolderRepository")
 */
class Folder
{
    const WRECK_REPORT_SENT = 'wreck-report-sent';
    const TO_BE_REFUND = 'to-be-refunded';
    const SUBMITTED = 'submitted';
    const CREATED = 'created';
    const TO_BE_RECONSEDERED = 'to-be-reconsidered';
    const REASSIGNED = 'reassigned';
    const IN_PROGRESS = 'in-progress';
    const SELLING_STANDBY = 'selling-standby';
    const CLOSED = 'closed';
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50,unique=true)
     */
    private $ref;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    /**
     * @ORM\Column(type="boolean", length=255, nullable=true)
     */
    private $refund;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $payment_amount;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $check_number;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $payment_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Expertise", mappedBy="folder", orphanRemoval=true)
     */
    private $expertises;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Vehicle", inversedBy="folders")
     */
    private $vehicle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bill", mappedBy="folder", orphanRemoval=true)
     */
    private $bills;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\WreckageReport")
     */
    private $wreckagereport;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AttachedFile", mappedBy="folder", orphanRemoval=true)
     */
    private $attachedFile;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Archive", mappedBy="folder", orphanRemoval=true)
     */
    private $archives;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $crashPoints;


    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isWreck;



    public function __construct()
    {
        $this->expertises = new ArrayCollection();
        $this->bills = new ArrayCollection();
        $this->attachedFile = new ArrayCollection();
        $this->archives = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getRefund(): ?string
    {
        return $this->refund;
    }

    public function setRefund(string $refund): self
    {
        $this->refund = $refund;

        return $this;
    }

    public function getPaymentAmount(): ?int
    {
        return $this->payment_amount;
    }

    public function setPaymentAmount(int $payment_amount): self
    {
        $this->payment_amount = $payment_amount;

        return $this;
    }

    public function getCheckNumber(): ?int
    {
        return $this->check_number;
    }

    public function setCheckNumber(int $check_number): self
    {
        $this->check_number = $check_number;

        return $this;
    }

    public function getPaymentDate(): ?\DateTimeInterface
    {
        return $this->payment_date;
    }

    public function setPaymentDate(\DateTimeInterface $payment_date): self
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    /**
     * @return Collection|Expertise[]
     */
    public function getExpertises(): Collection
    {
        return $this->expertises;
    }

    public function addExpertise(Expertise $expertise): self
    {
        if (!$this->expertises->contains($expertise)) {
            $this->expertises[] = $expertise;
            $expertise->setFolder($this);
        }

        return $this;
    }

    public function removeExpertise(Expertise $expertise): self
    {
        if ($this->expertises->contains($expertise)) {
            $this->expertises->removeElement($expertise);
            // set the owning side to null (unless already changed)
            if ($expertise->getFolder() === $this) {
                $expertise->setFolder(null);
            }
        }

        return $this;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): self
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    /**
     * @return Collection|Bill[]
     */
    public function getBills(): Collection
    {
        return $this->bills;
    }

    public function addBill(Bill $bill): self
    {
        if (!$this->bills->contains($bill)) {
            $this->bills[] = $bill;
            $bill->setFolder($this);
        }

        return $this;
    }

    public function removeBill(Bill $bill): self
    {
        if ($this->bills->contains($bill)) {
            $this->bills->removeElement($bill);
            // set the owning side to null (unless already changed)
            if ($bill->getFolder() === $this) {
                $bill->setFolder(null);
            }
        }

        return $this;
    }

    
    /**
     * @return Collection|AttachedFile[]
     */
    public function getAttachedFile(): Collection
    {
        return $this->attachedFile;
    }

    public function addAttachedFile(AttachedFile $attachedFile): self
    {
        if (!$this->attachedFile->contains($attachedFile)) {
            $this->attachedFile[] = $attachedFile;
            $attachedFile->setFolder($this);
        }

        return $this;
    }

    public function removeAttachedFile(AttachedFile $attachedFile): self
    {
        if ($this->attachedFile->contains($attachedFile)) {
            $this->attachedFile->removeElement($attachedFile);
            // set the owning side to null (unless already changed)
            if ($attachedFile->getFolder() === $this) {
                $attachedFile->setFolder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Archive[]
     */
    public function getArchives(): Collection
    {
        return $this->archives;
    }

    public function addArchive(Archive $archive): self
    {
        if (!$this->archives->contains($archive)) {
            $this->archives[] = $archive;
            $archive->setFolder($this);
        }

        return $this;
    }

    public function removeArchive(Archive $archive): self
    {
        if ($this->archives->contains($archive)) {
            $this->archives->removeElement($archive);
            // set the owning side to null (unless already changed)
            if ($archive->getFolder() === $this) {
                $archive->setFolder(null);
            }
        }

        return $this;
    }

    public function getCrashPoints(): ?array
    {
        return $this->crashPoints;
    }

    public function setCrashPoints(?array $crashPoints): self
    {
        $this->crashPoints = $crashPoints;

        return $this;
    }

    public function addCrashPoint($point)
    {
        $crashPoints = $this->getCrashPoints();
        if ($crashPoints == null) {
            $crashPoints = [];
        }
        array_push($crashPoints, $point);
        $this->setCrashPoints($crashPoints);
        return $this;
    }

    public function getisWreck(): ?bool
    {
        return $this->isWreck;
    }

    public function setisWreck(?bool $isWreck): self
    {
        $this->isWreck = $isWreck;

        return $this;
    }

    public function getWreckagereport(): ?WreckageReport
    {
        return $this->wreckagereport;
    }

    public function setWreckagereport(?WreckageReport $wreckagereport): self
    {
        $this->wreckagereport = $wreckagereport;

        return $this;
    }

}

src/Form/ExpertType.php
<?php

namespace App\Form;

use App\Entity\Expert;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class ExpertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [
                'required' => true,
                'constraints' => [
                    new Email([
                        'message' => "L'email '{{ value }}' est invalide",
                    ]),
                ],
            ])
            ->add('firstName', TextType::class, [
                'label' => 'Nom',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Vous devez entrer un nom',
                    ]),
                ],
            ])
            ->add('lastName', TextType::class, [
                'label' => 'Prenom',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Vous devez entrer un prenom',
                    ]),
                ],
            ])
            ->add('phoneNumber', NumberType::class, [
                'label' => 'N° de téléphone',
                'attr' => ['maxlength' => '8'],
                'required' => true,
            ])
            ->add('registration_tax_number', TextType::class, [
                'label' => 'Matricule fiscale',
                'required' => true,
            ])
            ->add('company_name', TextType::class, [
                'label' => 'Raison sociale',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Vous devez entrer le nom de l\'entreprise',
                    ]),
                ],
            ])
            ->add('address', TextType::class, [
                'label' => 'Adresse',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Vous devez entrer une adresse',
                    ]),
                ],
            ])
            ->add('city', ChoiceType::class, [
                'label' => 'Ville',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Vous devez choisir un pays',
                    ]),
                ],
                'choices' => [
                    'Tunis' => 'tunis',
                    'Sfax' => 'Sfax',
                    'Sousse' => 'Sousse',
                    'Bizerte' => 'bizerte',
                ]
            ])
            ->add('postal_code', NumberType::class, [
                'label' => 'Code postal',
                'attr' => ['maxlength' => '4'],
                'required' => true,
                'constraints' => [
                    new Regex([
                        'pattern' => '&^\d{4}$&',
                        'message' => 'Vous devez mettre un code postal 4 chiffre'
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Expert::class,
        ]);
    }
}

templates/insurance/expert/detailhistoryFolder.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}
{% block body %}

    <div class="w-75 mx-auto ">
        <h3 class="mb-3">Détail historique </h3>
        <div class="card mb-5">
            <div class="card-header">
                <span class="font-weight-bold"> Dossier  : </span>{{ archive.folder.ref }}
            </div>
            <div class="card-body">
                <table class="w-100">
                    <tbody>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Statut</th>
                        <td class="border-0">{{ archive.folder.state }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Remboursement</th>
                        <td class="border-0">{{ archive.folder.refund }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Numéro de chèque</th>
                        <td class="border-0">

                            {% if archive.folder.checkNumber is defined and archive.folder.checkNumber is not null %}
                                {{ archive.folder.paymentDate }}
                            {% else %}
                                0
                            {% endif %}
                        </td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">prix de Paiement</th>

                        <td class="border-0">
                            {% if archive.folder.paymentDate is defined and archive.folder.paymentDate is not null %}

                            {{ archive.folder.paymentDate }}
                            {% else %}
                            0
                            {% endif %}
                        </td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Véhicule</th>
                        <td class="border-0">{{ archive.folder.vehicle.type }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Matricule</th>
                        <td class="border-0">{{ archive.folder.vehicle.registrationNumber }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Nombre de chevaux</th>
                        <td class="border-0">{{ archive.folder.vehicle.registrationNumber }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Carte grise</th>
                        <td class="border-0">{{ archive.folder.vehicle.horsePower }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Assuré</th>
                        <td class="border-0">{{ archive.folder.vehicle.ensured.firstName|capitalize }} {{ archive.folder.vehicle.ensured.lastName|capitalize }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card mb-5">
            <div class="card-header">
                <span class="font-weight-bold">  Type d'action : </span> {{ archive.action }}
            </div>
            <div class="card-body">
                <table class="w-100">
                    <tbody>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Actionneur</th>
                        <td class="border-0">{{ archive.user.firstName|capitalize }} {{ archive.user.lastName|capitalize }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Le</th>
                        <td class="border-0">{{ archive.actionDate|date('y/m/d') }}</td>
                    </tr>
                    <tr class="border-0">
                        <th scope="row" class="border-0 text-success">Commentaire</th>
                        <td class="border-0">{{ archive.comments }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

templates/insurance/expert/foldersByStatus.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}

{% block body %}

    <div class="card mb-3  m-auto">
        <div class="card-header">
            <h3>
                <i class="fas fa-table"></i>
                {% if state == "created" %}
                    Liste des nouveaux dossiers
                {% elseif state == "in-progress" %}
                    Liste des dossiers en cours
                {% elseif state == "selling-standby" %}
                    Liste des dossier epaves
                {% elseif state == "closed" %}
                    Liste des dossiers en archive
                {% elseif state == "reassigned" %}
                    Liste des dossiers en contre expertise
                {% else %}
                    Liste des dossiers en retour
                {% endif %}
            </h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-sm" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th class="text-center " width="20%">Référence</th>
                        <th class="text-center " width="20%">Date affectation</th>
                        <th class="text-center " width="20%">Immatriculation</th>
                        <th class="text-center " width="20%">Client</th>
                        <th class="text-center " width="20%">Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('dataTabes') }}
{% endblock %}

templates/insurance/expert/historyFolder.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}

{% block body %}

    <div class="card mb-3">
        <div class="card-header">
            <h3>Détails du dossier {{ reference }}</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-sm" id="dataTable1"  width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th class="text-center">Statut</th>
                        <th class="text-center">Date d'action</th>
                        <th class="text-center">Type</th>
                        <th class="text-center">Action réalisée</th>
                        <th class="text-center">Détails</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('dataTabes') }}
{% endblock %}

templates/insurance/expert/home.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}
{% block body %}
    <div class="container-fluid">
        <h5 class="mb-3"><b>Bonjour  {{ app.user.firstName|capitalize }} {{ app.user.lastName|capitalize}} </b></h5>
        <div class="row">
            <div class="col-xl-7 col-lg-7 col-md-12 col-md-12 ">
                <div class="card-header text-center">
                    <i class="fas fa-chart-bar"></i>
                    Statistiques des dossiers du mois en cours
                </div>
                <div class="card-body">
                    <canvas id="myBarChart" width="100%" height="73%"></canvas>
                </div>
            </div>
            <div class="col-xl-5 col-lg-5 col-md-12 col-md-12 text-center">
                <div class="card-header">
                    <i class="fas fa-history"></i>
                    {% if tenHistoryFolders is defined and tenHistoryFolders is not null %}
                    Historique des opérations
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Référence</th>
                        <th scope="col">Statut</th>
                        <th scope="col">Date d'action</th>
                        <th scope="col">Type</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for tenHistoryFolder in tenHistoryFolders %}
                    <tr>
                        <th scope="row">{{ tenHistoryFolder.folder.ref }}</th>
                        <th scope="row">{{ tenHistoryFolder.folder.state }}</th>
                        <td>{{ tenHistoryFolder.action_date|date('y/m/d') }}</td>
                        <td>{{ tenHistoryFolder.type }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    Pas d'historique pour le moment
                {% endif %}
            </div>
        </div>

    </div>

{% endblock %}

    {% block javascripts %}
        {{ parent() }}
        {{ encore_entry_script_tags('pluginCharts') }}
        {{ encore_entry_script_tags('chartFolderExpert') }}
    {% endblock %}

templates/insurance/expert/myPaiement.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}
{% block body %}
    <div class="card">
        <div class="card-header bg-info d-flex justify-content-between">
            <h4 style="color: white"><i class="fas fa-list-ul"></i> Liste des paiements</h4>

        </div>
        <div class="col-xl-3 col-sm-6 mb-4 " style="margin-top: 50px">

        </div>

        <div class="container">
            <div class="table-responsive">
                <table class="table table-hover mt-3">
                    <thead>
                    <tr>
                        <th>Réference de paiement</th>
                        <th>Remboursement </th>
                        <th>date de remboursement</th>
                        <th>Details</th>
                    </tr>


                    </thead>
                    {% if expertises is not empty %}
                        {% for expertise in expertises %}

                            <tr>
                                <td>{{ expertise.getPaiment.reference }}</td>
                                <td>{{ expertise.getPaiment.getAmount }}</td>
                                <td>{{ expertise.getPaiment.getPaimentDate |date }} </td>
                                <td><a href="{{ path('paiementDetail',{'id':expertise.getPaiment.id}) }}"><i class=" btn btn-info fas fa-search"></i></a></td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </table>
            </div></div></div>

{% endblock %}

templates/insurance/expert/paiementDetail.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info d-flex justify-content-between">
            <h4 style="color: white"><i class="fas fa-list-ul"></i> Liste des dossiers remboursés </h4>

        </div>
        <div class="col-xl-3 col-sm-6 mb-4 " style="margin-top: 50px">

        </div>
        <div class="container">
            <div class="table-responsive">
                <table class="table table-hover mt-3">
                    <thead>
                    <tr>
                        <th class="text-center">Référence de dossier</th>
                        <th class="text-center">Matricule de voiture</th>
                        <th class="text-center" >Honoraire</th>
                        <th class="text-center" >Etat de dossier</th>

                    </tr>
                    {% for refundedFolder in folders %}
                        <tr>
                            <td class="text-center">{{ refundedFolder.folder.ref }}</td>
                            <td class="text-center">{{ refundedFolder.folder.vehicle.registrationNumber }}</td>
                            <td class="text-center">{{ refundedFolder.honorary }}</td>
                            <td class="text-center">{{ refundedFolder.folder.state }}</td>

                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        </tbody>
        </table>

    </div>
{% endblock %}

templates/insurance/expert/profile.html.twig
{% extends 'insurance/expert/skeleton/baseExpert.html.twig' %}
{% block body %}
    {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="alert alert-danger">
            {{ flashMessage }}
        </div>
    {% endfor %}
<div class="card">
    <h4 class="card-header">Modifier Votre compte</h4>
    <div class="d-flex card-body">
    <div class="col-6">
        <h1>{{ expert.firstName~' '~expert.lastName}}</h1><br>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Modifier">
        </div>
        {{ form_end(form) }}
    </div>
    </div>
</div>
{% endblock %}