src/Entity/Bill.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BillRepository")
 */
class Bill
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $setDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $bill_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bill_ref;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $works;

    /**
     * @ORM\Column(type="float")
     */
    private $realAmount;

    /**
     * @ORM\Column(type="float")
     */
    private $estimaedAmount;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Folder", inversedBy="bills")
     * @ORM\JoinColumn(nullable=true)
     */
    private $folder;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Archive", mappedBy="bill")
     */
    private $archives;

    public function __construct()
    {
        $this->archives = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSetDate(): ?\DateTimeInterface
    {
        return $this->setDate;
    }

    public function setSetDate(\DateTimeInterface $setDate): self
    {
        $this->setDate = $setDate;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getBillDate(): ?\DateTimeInterface
    {
        return $this->bill_date;
    }

    public function setBillDate(\DateTimeInterface $bill_date): self
    {
        $this->bill_date = $bill_date;

        return $this;
    }

    public function getBillRef(): ?string
    {
        return $this->bill_ref;
    }

    public function setBillRef(string $bill_ref): self
    {
        $this->bill_ref = $bill_ref;

        return $this;
    }

    public function getWorks(): ?string
    {
        return $this->works;
    }

    public function setWorks(string $works): self
    {
        $this->works = $works;

        return $this;
    }

    public function getRealAmount(): ?float
    {
        return $this->realAmount;
    }

    public function setRealAmount(float $realAmount): self
    {
        $this->realAmount = $realAmount;

        return $this;
    }

    public function getEstimaedAmount(): ?float
    {
        return $this->estimaedAmount;
    }

    public function setEstimaedAmount(float $estimaedAmount): self
    {
        $this->estimaedAmount = $estimaedAmount;

        return $this;
    }

    public function getFolder(): ?Folder
    {
        return $this->folder;
    }

    public function setFolder(?Folder $folder): self
    {
        $this->folder = $folder;

        return $this;
    }

    /**
     * @return Collection|Archive[]
     */
    public function getArchives(): Collection
    {
        return $this->archives;
    }

    public function addArchive(Archive $archive): self
    {
        if (!$this->archives->contains($archive)) {
            $this->archives[] = $archive;
            $archive->setBill($this);
        }

        return $this;
    }

    public function removeArchive(Archive $archive): self
    {
        if ($this->archives->contains($archive)) {
            $this->archives->removeElement($archive);
            // set the owning side to null (unless already changed)
            if ($archive->getBill() === $this) {
                $archive->setBill(null);
            }
        }

        return $this;
    }
}

src/Entity/Expert.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExpertRepository")
 */
class Expert extends User
{


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $registration_tax_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $postal_code;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Expertise", mappedBy="expert")
     */
    private $expertises;

    public function __construct()
    {
        $this->expertises = new ArrayCollection();
    }

    public function getRegistrationTaxNumber(): ?string
    {
        return $this->registration_tax_number;
    }

    public function setRegistrationTaxNumber(string $registration_tax_number): self
    {
        $this->registration_tax_number = $registration_tax_number;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    /**
     * @return Collection|Expertise[]
     */
    public function getExpertises(): Collection
    {
        return $this->expertises;
    }

    public function addExpertise(Expertise $expertise): self
    {
        if (!$this->expertises->contains($expertise)) {
            $this->expertises[] = $expertise;
            $expertise->setExpert($this);
        }

        return $this;
    }

    public function removeExpertise(Expertise $expertise): self
    {
        if ($this->expertises->contains($expertise)) {
            $this->expertises->removeElement($expertise);
            // set the owning side to null (unless already changed)
            if ($expertise->getExpert() === $this) {
                $expertise->setExpert(null);
            }
        }

        return $this;
    }

}

templates/insurance/details/ensured.html.twig
<div class="card">
    <h4 class="card-header"> <i class="fas fa-user-injured"></i> L'assuré</h4>
    <div class="d-flex card-body">
        <div class="col-6">
            <p>
                <span class="font-weight-bold text-success">Nom et prénom : </span>{{ folder.vehicle.ensured.firstName~' '~folder.vehicle.ensured.lastName }}
            </p>
            <p>
                <span class="font-weight-bold text-success">N° CIN : </span>{{ folder.vehicle.ensured.cin }}
            </p>
            <p>
                <span class="font-weight-bold text-success">N° téléphone : </span>{{ folder.vehicle.ensured.phone }}
            </p>
            <p>
                <span class="font-weight-bold text-success">Email  : </span>{{ folder.vehicle.ensured.email }}
            </p>
        </div>
        <div class="col-6">
            <p><span class="font-weight-bold text-success">Adresse : </span></p>
            <p>
                <span class="font-weight-bold text-success">Ville : </span>{{ folder.vehicle.ensured.city }}
            </p>
            <p>
                <span class="font-weight-bold text-success">Code postal : </span>{{ folder.vehicle.ensured.zipCode }}
            </p>
        </div>
    </div>
</div>

templates/insurance/details/expert.html.twig
<div class="card">
    <h4 class="card-header"><i class="fas fa-user-edit"></i> L'expert en charge:</h4>
    <div class="d-flex card-body">
        <div class="col-6">
            <p><span class="font-weight-bold text-success">Nom complet: </span>{{ expert.firstName~' '~expert.lastName }}
            </p>
            <p>
                <span class="font-weight-bold text-success">N° Tel: </span>{{ expert.phoneNumber }}
            </p>
        </div>
        <div class="col-6">
            <p>
                <span class="font-weight-bold text-success">Matricule fiscale:: </span>{{ expert.registrationTaxNumber }}
            </p>
            <p>
                <span class="font-weight-bold text-success">Nom de la societe: </span>{{ expert.companyName }}
            </p>
        </div>
    </div>
</div>

templates/insurance/details/faturesList.html.twig
<div class="card">
    <h4 class="card-header"><i class="fas fa-file-invoice-dollar"></i> Liste des factures</h4>
    {% if folder.bills is not empty %}
        <div class="d-flex card-body container">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="thead-dark">
                    <tr>
                        <th>réference de facture</th>
                        <th>type de facture</th>
                        <th>date de facture</th>
                        <th>date de saisie de facture</th>
                        <th>travaux</th>
                        <th>montant réel</th>
                        <th>montant estimé</th>
                    </tr>
                    </thead>
                    {% for bill in folder.bills %}
                        <tr>
                            <td class="table-active">{{ bill.billRef }}</td>
                            <td class="table-active">{{ bill.type }}</td>
                            <td class="table-active">{{ bill.billDate|date("m/d/Y H:i") }}</td>
                            <td class="table-active">{{ bill.setDate|date("m/d/Y H:i") }}</td>
                            <td class="table-active">{{ bill.works }}</td>
                            <td class="table-active">{{ bill.realAmount }}</td>
                            <td class="table-active">{{ bill.estimaedAmount }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    {% else %}
        <h3>Pas de factures</h3>
    {% endif %}
</div>

templates/insurance/details/imagesList.html.twig
<div class="card">
    <h4 class="card-header"><i class="fas fa-images"></i> {{ listTitle }}</h4>
    <div class="d-flex card-body">
        {% for image in folder.attachedFile %}
            {% if image.type == type %}
                <div style="position: relative; display: inline-block;">
                    <img height="200" src="data:image/png;base64,{{ image.fileBase64 }}"
                         alt="">
                    <div style="position: absolute; top: 0;right: 0;" class="imageValidation">
                        <input type="hidden" value="{{ image.id }}" class="idImage">
                        <input type="hidden" value="{{ image.validated }}" class="statusImage">
                        {% if is_granted('ROLE_VALIDATOR') %}
                            <div class="imageValidator">
                                {% if image.validated == true %}
                                    <i class="fas fa-check fa-2x text-success"></i>
                                {% else %}
                                    <i class="fas fa-times fa-2x text-danger"></i>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

templates/insurance/details/vehicle.html.twig
<div class="card">
    <h4 class="card-header"> <i class="fas fa-car"></i> Véhicule concernée</h4>
    <div class="d-flex card-body">
        <div class="col-6">
            <p><span class="font-weight-bold text-success">Type : </span>{{ folder.vehicle.type }}
            </p>
            <p>
                <span class="font-weight-bold text-success">N° d'immatriculation : </span>{{ folder.vehicle.registrationNumber }}
            </p>
            <p>
                <span class="font-weight-bold text-success">Puissance fiscale : </span>{{ folder.vehicle.horsePower }}
            </p>
        </div>
        <div class="col-6">
            <p>
                <span class="font-weight-bold text-success">Date de 1ère mise en circulation : </span>{{ folder.vehicle.dateOfRegistration|date("d/m/Y") }}
            </p>
            <p>
            <span class="font-weight-bold text-success">Nombre de portes : </span>{{ folder.vehicle.doorsNumber }}
            </p>
            <p>
                <span class="font-weight-bold text-success">Couleur : </span>{{ folder.vehicle.color }}
            </p>
        </div>
    </div>
</div>

templates/insurance/details/wreckReport.html.twig
<div class="card">
    <h4 class="card-header"><i class="fas fa-list"></i> Details de rapport d'épave:</h4>
    <div class="d-flex flex-column card-body">
        <h5>Sujet : Demande de dossier épave pour le véhicule
            immatriculé {{ folder.vehicle.registrationNumber }}</h5><br>
        <h6>Déroulement de l'accident :</h6>
        <p>
            <span class="font-weight-bold text-danger"
                 id="expertCommentsField">{{ wreckReportDetails.comments }}
            </span>
        </p>

        <p>Nous avons estimé la valeur du véhicule, le jour de l'accident, à
            <span class="font-weight-bold text-danger" id="estimatedPriceField">
                {{ wreckReportDetails.estimatedCarPrice }}
            </span> DT et vu l'estimation des frais de
            réparation qui s'élèvent à
            <span class="font-weight-bold text-danger" id="estimatedReparationsField">
                {{ wreckReportDetails.repairAmount }}
            </span>
            DT et qui
            plus de 50 % du prix du véhicule; nous avons proposé de le vendre en épave.
        </p>
        {#<div class="col-6">#}
            {#<p><span class="font-weight-bold text-success">Prix estimé de voiture: </span>{{ wreckReportDetails.estimatedCarPrice }}dt</p>#}
            {#<p><span class="font-weight-bold text-success">Prix estimé de réparation: </span>{{ wreckReportDetails.repairAmount }} dt</p>#}
            {#<p><span class="font-weight-bold text-success">Prix estimé de vente: </span>{{ wreckReportDetails.sellingPrice  }} dt</p>#}
        {#</div>#}
        {#<div class="col-6">#}
            {#<p><span class="font-weight-bold text-success">Commentaires:</span> {{ wreckReportDetails.comments }}</p>#}
        {#</div>#}
    </div>
</div>