src/Entity/Expert.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExpertRepository")
 */
class Expert extends User
{


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $registration_tax_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $postal_code;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Expertise", mappedBy="expert")
     */
    private $expertises;

    public function __construct()
    {
        $this->expertises = new ArrayCollection();
    }

    public function getRegistrationTaxNumber(): ?string
    {
        return $this->registration_tax_number;
    }

    public function setRegistrationTaxNumber(string $registration_tax_number): self
    {
        $this->registration_tax_number = $registration_tax_number;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    /**
     * @return Collection|Expertise[]
     */
    public function getExpertises(): Collection
    {
        return $this->expertises;
    }

    public function addExpertise(Expertise $expertise): self
    {
        if (!$this->expertises->contains($expertise)) {
            $this->expertises[] = $expertise;
            $expertise->setExpert($this);
        }

        return $this;
    }

    public function removeExpertise(Expertise $expertise): self
    {
        if ($this->expertises->contains($expertise)) {
            $this->expertises->removeElement($expertise);
            // set the owning side to null (unless already changed)
            if ($expertise->getExpert() === $this) {
                $expertise->setExpert(null);
            }
        }

        return $this;
    }

}

templates/insurance/sinister/admin/agentDetails.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}
{% block body %}
    <div class="card">
        <h4 class="card-header bg-info" style="color: white"><i class="fas fa-user-edit" style="color: white"></i> Les
            informations de {{ role }}:</h4>
        <div class="container">

            <div class="row" style="margin-top: 50px">
                <div class="col-9 offset-1">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <th>Nom</th>
                            <td>{{ agent.lastName }}</td>
                        </tr>
                        <tr>
                            <th>Prénom</th>
                            <td>{{ agent.firstName }}</td>
                        </tr>
                        <tr>
                            <th>phoneNumber</th>
                            <td>{{ agent.phoneNumber }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ agent.email }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-12 d-flex flex-md-row-reverse">
                            <a href="{{ path('agentUpdate',{'id':agent.id}) }}">
                                <button class="btn btn-outline-dark">
                                    <i class="fas fa-edit"></i> Modifier
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/insurance/sinister/admin/expertDetails.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}
{% block body %}

    <div class="card">
        <h4 class="card-header bg-info" style="color: white"><i class="fas fa-user-edit" style="color: white"></i> Les
            informations de l'expert:</h4>
        <div class="container">

            <div class="row" style="margin-top: 50px">
                <div class="col-9 offset-1">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <th>Nom complet</th>
                            <td>{{ expert.firstName~' '~expert.lastName }}</td>
                        </tr>
                        <tr>
                            <th>phoneNumber</th>
                            <td>{{ expert.phoneNumber }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ expert.email }}</td>
                        </tr>
                        <tr>
                            <th>Matricule fiscale</th>
                            <td>{{ expert.registrationTaxNumber }}</td>
                        </tr>
                        <tr>
                            <th>Adresse</th>
                            <td>{{ expert.city }} {{ expert.postalCode }} {{ expert.address }}</td>
                        </tr>

                        <tr>
                            <th>Nom de la societe</th>
                            <td>{{ expert.companyName }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-12 d-flex flex-md-row-reverse">
                            <a href="{{ path('expertUpdate',{'id':expert.id}) }}">
                                <button class="btn btn-outline-dark">
                                    <i class="fas fa-edit"></i> Modifier
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/insurance/sinister/admin/folderConfiguration.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="col-xl-3 col-sm-6 mb-4">
        <a href="{{ path('home-sinister') }}">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body supp_pad">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-folder"></i>
                    </div>
                    <div class="mr-5">Retour</div>
                </div>
            </div>
        </a>
    </div>
    <h1>Paramétres des dossiers : </h1>

{% endblock %}

templates/insurance/sinister/admin/listExpert.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}

    <div class="card">
        <div class="card-header bg-info d-flex justify-content-between">
            <h4 style="color: white"><i class="fas fa-list-ul"></i> Liste des experts</h4>

            <a href="{{ path('new-expert') }}">
                <button class="btn btn-info border-white "><i class="fas fa-plus-square"></i> Ajouter un expert</button>
            </a>
        </div>
        <div class="col-xl-3 col-sm-6 mb-4 " style="margin-top: 50px">

        </div>
        <div class="container">


            <table id="listExpert" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Téléphone</th>
                    <th>Email</th>
                    <th>Matricule Fiscale</th>
                    <th>Raison</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('listExpert') }}
    {{ encore_entry_script_tags('dataTabes') }}

{% endblock %}

templates/insurance/sinister/admin/listFinancial.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info d-flex justify-content-between">
            <h4 style="color: white"><i class="fas fa-user-edit"></i> Liste des financiers</h4>

            <a href="{{ path('new-insurer', {'role' : 'financial'}) }}">
                <button class="btn btn-info border-white "><i class="fas fa-plus-square"></i> Ajouter un financier</button>
            </a>
        </div>
        <div class="col-xl-3 col-sm-6 mb-4 " style="margin-top: 50px">

        </div>
        <div class="container">


            <table id="listFinancier" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Téléphone</th>
                    <th>Email</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('listExpert') }}
{% endblock %}

templates/insurance/sinister/admin/listReceptionist.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info d-flex justify-content-between">
            <h4 style="color: white"><i class="fas fa-list-ul"></i> Liste des réceptionnistes</h4>

            <a href="{{ path('new-insurer', {'role' : 'receptionist'}) }}">
                <button class="btn btn-info border-white "><i class="fas fa-plus-square"></i> Ajouter un réceptionniste</button>
            </a>
        </div>
        <div class="col-xl-3 col-sm-6 mb-4 " style="margin-top: 50px">

        </div>
        <div class="container">


            <table id="listReceptionnist" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Téléphone</th>
                    <th>Email</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('listExpert') }}
{% endblock %}

templates/insurance/sinister/admin/listValidator.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info d-flex justify-content-between">
            <h4 style="color: white"><i class="fas fa-list-ul"></i> Liste des validateurs</h4>

            <a href="{{ path('new-insurer', {'role' : 'validator'}) }}">
                <button class="btn btn-info border-white "><i class="fas fa-plus-square"></i> Ajouter un validateur</button>
            </a>
        </div>
        <div class="col-xl-3 col-sm-6 mb-4 " style="margin-top: 50px">

        </div>
        <div class="container">


            <table id="listValidateur" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Téléphone</th>
                    <th>Email</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('listExpert') }}
{% endblock %}

templates/insurance/sinister/admin/newExpert.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info">
            <h4 style="color: white"><i class="fas fa-user-plus"></i> Ajouter un nouveau expert</h4>
        </div>
        <div class="d-flex card-body">
            <div class="col-6">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                {{ form_widget(form) }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Ajouter Expert">
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/insurance/sinister/admin/newFinancial.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info">
            <h4 style="color: white"><i class="fas fa-user-plus"></i> Ajouter un nouveau financier</h4>
        </div>
        <div class="d-flex card-body">
            <div class="col-6">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Ajouter Financier">
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/insurance/sinister/admin/newReceptionist.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info">
            <h4 style="color: white"><i class="fas fa-user-plus"></i> Ajouter un nouveau receptionniste</h4>
        </div>
        <div class="d-flex card-body">
            <div class="col-6">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Ajouter Receptionniste">
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/insurance/sinister/admin/newValidator.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header bg-info">
            <h4 style="color: white"><i class="fas fa-user-plus"></i> Ajouter un nouveau validateur</h4>
        </div>
        <div class="d-flex card-body">
            <div class="col-6">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Ajouter Validateur">
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/insurance/sinister/admin/updateAgent.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <h4 class="card-header bg-info" style="color: white"><i class="fas fa-user-edit"></i>Modifier {{ role }}</h4>
        <div class="d-flex card-body">
            <div class="col-6">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Modifier {{ role }}">
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/insurance/sinister/admin/updateExpert.html.twig
{% extends 'insurance/sinister/skeleton_page/baseSinistre.html.twig' %}

{% block body %}
    <div class="card">
        <h4 class="card-header bg-info" style="color: white"><i class="fas fa-user-edit"></i>Modifier Expert</h4>
        <div class="d-flex card-body">
            <div class="col-6">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Modifier Expert">
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}